version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/SoloFlow/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/SoloFlow/backend"
    schedule:
      interval: "weekly"